[build]
  command = "npm start"  # Adjust this based on your start script
  functions = "backend"  # This assumes your serverless functions are in the "functions" directory        
  environment = { NETLIFY_FUNCTION = "true" }
